common: Do not require dirtyRev
Follow up to 7ccbd260334a80212b61c7ef90ab370eeb822383.

Using out-of-flake Nixpkgs in nopt somehow does not set the flake attribute:

   $ nopt -I nixpkgs=$HOME/Projects/nixpkgs environment.variables

   error: attribute 'dirtyRev' missing