flake: update
- Needed to disable qmk udev rules for now since the PR has not been merged yet.
- Use spiceUSBRedirection module instead of replicating it manually, since that fails with
  the following error due to changes in https://github.com/NixOS/nixpkgs/pull/126289:

      error: The option `security.wrappers.spice-client-glib-usb-acl-helper.owner' is used but not defined.