azazel: use phpBB declaratively
forum.fcp.cz now uses latest phpBB and the software is installed by Nix.
It needs some writeable directories so they have to be symlinked to
/var/www/fan-club-penguin.cz/cpforum and /var/cache/cpforum.

Additionally, we are running the forum under a different user to increase security.

There are several issues still:
- The phpfpm services run as root so the created cache directory will be owned by root. We need to hack around it by tmpfiles.d.
- The files in the cache seem to be created as root, we need to manually chmod them before upgrading.
- The CLI migration tool `nix shell -f channel:nixos-unstable php -c sudo -u cpforum php bin/phpbbcli.php --safe-mode db:migrate` does not seem to work:
    Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: A string value must be composed of strings and/or numbers, but found parameter "core.table_prefix" of type "NULL" inside string value "%core.table_prefix%oauth_tokens". in /nix/store/7z0w0v3ba74dhxmi4qw0y6zk0hc9dnm0-phpbb-3.3.1/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:237
  We need to enable the installer declaratively and then update the database by visiting <https://forum.fan-club-penguin.cz/install/app.php/update>.