homeConfigurations.brian: Fix system eval
It was failing with

    error: The 'homeManagerConfiguration' arguments

         - 'configuration',
         - 'username',
         - 'homeDirectory'
         - 'stateVersion',
         - 'extraModules', and
         - 'system'

       have been removed. Instead use the arguments 'pkgs' and
       'modules'. See the 22.11 release notes for more.

https://github.com/nix-community/home-manager/commit/f26946858e07384860bf288f20e39a8d32ed5b71