flake.lock: Update
Flake lock file updates:

• Updated input 'c4':
    'github:fossar/composition-c4/2175e6fc35126255ca51fe6dec978f93f3ce7464' (2022-05-27)
  → 'github:fossar/composition-c4/493ddc4a8279cde3bee0db1d04fd7d4838d51ab9' (2023-03-29)

• Updated input 'home-manager':
    'github:nix-community/home-manager/db37c537603d1d45d022cc0666ad45197455b364' (2023-03-24)
  → 'github:nix-community/home-manager/765e4007b6f9f111469a25d1df6540e8e0ca73a6' (2023-03-28)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/19cf008bb18e47b6e3b4e16e32a9a4bdd4b45f7e' (2023-03-21)
  → 'github:nixos/nixpkgs/4bb072f0a8b267613c127684e099a70e1f6ff106' (2023-03-27)

Also drop fractal since it is broken:

    ERROR: The Cargo.lock contains git dependencies

    This is currently not supported in the fixed-output derivation fetcher.
    Use cargoLock.lockFile / importCargoLock instead.